#!/bin/bash

clear
echo -e "                 CELCOM                      "
echo -e "Name                  : Celcom"
echo -e "APN                   : www.xlmms.net "
echo -e "Proxy                 : Not set" 
echo -e "Port                  : Not set"
echo -e "Username              : mms"
echo -e "Password              : celcom"
echo -e "Server                : Not Set"
echo -e "MMSC                  : Not set"
echo -e "MMS proxy             : Not set"
echo -e "MMS port              : Not set"
echo -e "MCC                   : 502"
echo -e "MNC                   : 19"
echo -e "Authentication type   : PAP"
echo -e "APN type              : default,supl,mms"
echo -e "APN protocol          : ipv4/ipv6"
echo -e "APN roaming Protocol  : ipv4/ipv6"
