#!/bin/bash

clear
echo -e "                 MAXIS                     "
echo -e "Name                  : Maxis 4G"
echo -e "APN                   : hos "
echo -e "Proxy                 : Not set" 
echo -e "Port                  : Not set"
echo -e "Username              : maxis"
echo -e "Password              : wap"
echo -e "Server                : Not Set"
echo -e "MMSC                  : http://172.16.74.100:10021/mmsc"
echo -e "MMS proxy             : 202.75.133.49"
echo -e "MMS port              : 80"
echo -e "MCC                   : 502"
echo -e "MNC                   : 12"
echo -e "Authentication type   : PAP"
echo -e "APN type              : default,supl,mms"
echo -e "APN protocol          : ipv4/ipv6"
echo -e "APN roaming Protocol  : ipv4/ipv6"
